twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    paths:
        # pointe vers votre dossier d'images
        '%kernel.project_dir%/public/img': images
when@test:
    twig:
        strict_variables: true
